CREATE TABLE CONSULTA(
    IDCONSULTA INTEGER PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CITA INTEGER,
    DIAGNOSTICO VARCHAR(50),
    CONSTRAINT FKIDCITA FOREIGN KEY (CITA) REFERENCES CITA(IDCITA)
)