/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examencomponentes;

/**
 *
 * @author Zidai
 */
public class Polinomio extends javax.swing.JPanel {
    
    private boolean miembro3, miembro4;
    int miembros;
    /**
     * Creates new form Polinomio
     */
    public Polinomio() {
        initComponents();
        miembros=2;
        jLabel3.setVisible(false);
        campoTextoNumerico3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        campoTextoNumerico4.setVisible(false);
        jLabel6.setVisible(false);
        miembro3 = false;
        miembro4 = false;
        
    }
    
    public void setMiembro3(boolean b){
        if(b == true){
            jLabel3.setVisible(b);
            campoTextoNumerico3.setVisible(b);
            jLabel4.setVisible(b);
            //reveal(jLabel1);
            miembro3 = b;
        }
        if(b == false){
            jLabel3.setVisible(b);
            campoTextoNumerico3.setVisible(b);
            jLabel4.setVisible(b);
            //hide(jLabel1);
            miembro3 = b;
        }
    }
    
    public void setMiembro4(boolean b){
        if(b == true){
            jLabel5.setVisible(b);
            campoTextoNumerico4.setVisible(b);
            jLabel6.setVisible(b);
            //reveal(jLabel1);
            miembro3 = b;
        }
        if(b == false){
            jLabel5.setVisible(b);
            campoTextoNumerico4.setVisible(b);
            jLabel6.setVisible(b);
            //hide(jLabel1);
            miembro3 = b;
        }
    }
    
    public void setMiembros(int b){
        
        if(b == 2){
            jLabel3.setVisible(true);
            campoTextoNumerico3.setVisible(true);
            jLabel4.setVisible(true);
            //reveal(jLabel1);
        }
        if(b == 3){
            jLabel3.setVisible(false);
            campoTextoNumerico3.setVisible(false);
            jLabel4.setVisible(false);
            //hide(jLabel1);
            
            
        }
    }
    
    public void reveal(javax.swing.JLabel j){
        j.setVisible(true);
    }
    
    public void hide(javax.swing.JLabel j){
        j.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        campoTextoNumerico1 = new componentecampotexto.CampoTextoNumerico();
        jLabel1 = new javax.swing.JLabel();
        campoTextoNumerico2 = new componentecampotexto.CampoTextoNumerico();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campoTextoNumerico3 = new componentecampotexto.CampoTextoNumerico();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoTextoNumerico4 = new componentecampotexto.CampoTextoNumerico();
        jLabel6 = new javax.swing.JLabel();
        campoTextoNumerico5 = new componentecampotexto.CampoTextoNumerico();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        campoTextoNumerico6 = new componentecampotexto.CampoTextoNumerico();
        jLabel8 = new javax.swing.JLabel();

        campoTextoNumerico1.setLimMax(10000);
        campoTextoNumerico1.setLimMin(0);
        campoTextoNumerico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNumerico1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("+");

        campoTextoNumerico2.setLimMax(1000000);
        campoTextoNumerico2.setLimMin(0);
        campoTextoNumerico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNumerico2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("x");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("+");

        campoTextoNumerico3.setLimMax(10000);
        campoTextoNumerico3.setLimMin(0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("x^2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("+");

        campoTextoNumerico4.setLimMax(10000);
        campoTextoNumerico4.setLimMin(0);
        campoTextoNumerico4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTextoNumerico4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("x^3");

        campoTextoNumerico5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTextoNumerico5.setLimMax(10000);
        campoTextoNumerico5.setLimMin(0);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Escribe un valor para X");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        campoTextoNumerico6.setLimMax(10000);
        campoTextoNumerico6.setLimMin(0);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoTextoNumerico1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoNumerico2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoNumerico3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoTextoNumerico5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoTextoNumerico4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTextoNumerico6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNumerico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(campoTextoNumerico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(campoTextoNumerico3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(campoTextoNumerico4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTextoNumerico5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoNumerico6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoTextoNumerico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNumerico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNumerico1ActionPerformed

    private void campoTextoNumerico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNumerico2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNumerico2ActionPerformed

    private void campoTextoNumerico4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTextoNumerico4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTextoNumerico4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float a=Float.parseFloat(campoTextoNumerico1.getText());
        float b=Float.parseFloat(campoTextoNumerico2.getText());
        float c=0;
        float d=0;
        float x=Float.parseFloat(campoTextoNumerico5.getText());
        float resultado=0;
        if(campoTextoNumerico3.isVisible()){
            c=Float.parseFloat(campoTextoNumerico3.getText());
        }
        if(campoTextoNumerico4.isVisible()){
            d=Float.parseFloat(campoTextoNumerico4.getText());
        }
        
        resultado= a+(b*x);
        if(campoTextoNumerico3.isVisible()){
            resultado=resultado+(c*((float)Math.pow(x, 2)));
        }
        if(campoTextoNumerico4.isVisible()){
            resultado=resultado+(d*((float)Math.pow(x, 3)));
        }
        
        campoTextoNumerico6.setText(""+resultado);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico1;
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico2;
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico3;
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico4;
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico5;
    private componentecampotexto.CampoTextoNumerico campoTextoNumerico6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
