/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentepregunta;
import java.io.Serializable;
import javax.swing.JPanel;
/**
 *
 * @author Zidai
 */
public class Pregunta extends JPanel implements Serializable{
    private String pregunta;
    private String respuesta1;
    private String respuesta2;
    private String respuesta3;
    private int respuestaCorrecta;
    /**
     * Creates new form Pregunta
     */
    public Pregunta() {
        initComponents();
        respuestaCorrecta=1;
        pregunta = "Escribe aqui tu pregunta";
        jLabel1.setText(pregunta);
        opcionQuestionario1.setEsCorrecta(true);
        respuesta1 = "Escrebe respuesta opcional 1";
        opcionQuestionario1.setText(respuesta1);
        opcionQuestionario2.setEsCorrecta(false);
        respuesta2 = "Escribe respuesta opcional 2";
        opcionQuestionario2.setText(respuesta2);
        opcionQuestionario3.setEsCorrecta(false);
        respuesta3 = "Escribe respuesta opcional 3";
        opcionQuestionario3.setText(respuesta3);
    }
    
    public int getRespuestaCorrecta(){
        return respuestaCorrecta;
    }
    public void setRespuestaCorrecta(int res){
        if(res>3||res<=0){
            
        }
        else if(res==1){
            opcionQuestionario1.setEsCorrecta(true);
            opcionQuestionario2.setEsCorrecta(false);
            opcionQuestionario3.setEsCorrecta(false);
        }
        else if(res==2){
            opcionQuestionario1.setEsCorrecta(false);
            opcionQuestionario2.setEsCorrecta(true);
            opcionQuestionario3.setEsCorrecta(false);
        }
        else if(res==3){
            opcionQuestionario1.setEsCorrecta(false);
            opcionQuestionario2.setEsCorrecta(false);
            opcionQuestionario3.setEsCorrecta(true);
        }
    }
    
    public void setPregunta(String p){
        jLabel1.setText(pregunta);
    }
    
    public void setRespuesta1(String r){
        opcionQuestionario1.setText(respuesta1);
    }
    
    public void setRespuesta2(String r){
        opcionQuestionario2.setText(respuesta2);
    }
    
    public void setRespuesta3(String r){
        opcionQuestionario3.setText(respuesta3);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        opcionQuestionario1 = new componentecompuestopractica.OpcionQuestionario();
        opcionQuestionario2 = new componentecompuestopractica.OpcionQuestionario();
        opcionQuestionario3 = new componentecompuestopractica.OpcionQuestionario();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Escribe aqui tu pregunta");

        buttonGroup1.add(opcionQuestionario1);
        opcionQuestionario1.setText("opcionQuestionario1");

        buttonGroup1.add(opcionQuestionario2);
        opcionQuestionario2.setText("opcionQuestionario2");

        buttonGroup1.add(opcionQuestionario3);
        opcionQuestionario3.setText("opcionQuestionario3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opcionQuestionario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcionQuestionario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opcionQuestionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(opcionQuestionario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionQuestionario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opcionQuestionario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private componentecompuestopractica.OpcionQuestionario opcionQuestionario1;
    private componentecompuestopractica.OpcionQuestionario opcionQuestionario2;
    private componentecompuestopractica.OpcionQuestionario opcionQuestionario3;
    // End of variables declaration//GEN-END:variables
}
